spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://117.72.82.38:3306/time_flow?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Senge520...
  web:
    resources:
      static-locations: classpath:/web/
sa-token:
  token-name: token
  # Jwt 密钥
  jwt-secret-key: senge520
  # 不写入 Cookie
  is-read-cookie: false
system:
  cors-enable: true # 是否开启跨域
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl