spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://117.72.82.38:3306/time_flow?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Senge520...
sa-token:
  token-name: token
  # Jwt 密钥
  jwt-secret-key: senge520
  # 不写入 Cookie
  is-read-cookie: false