spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://117.72.82.38:3306/time_flow?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
sa-token:
  token-name: token
