server:
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.221.136.224:3306/goal?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Senge520...
  web:
    resources:
      static-locations: classpath:/web/
  threads:
    virtual:
      enabled: true
sa-token:
  token-name: token
  # Jwt 密钥
  jwt-secret-key: senge520
  # 不写入 Cookie
  is-read-cookie: false
system:
  cors-enable: true # 是否开启跨域
qiniu:
  host: http://t40u7w44h.hb-bkt.clouddn.com/
  accessKey: ovborwx3hGPexZVZ25DKFoTXQ0ZNAcJlSkLt9sdz
  secretKey: MG9uKh8FcEaxa4pHdghc5uX3q7B8igEpLJZlzKPw
  bucket: xiaoyao-diary
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl